# Generated by Django 5.2.5 on 2025-10-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='waiting_review',
            field=models.BooleanField(default=False),
        ),
    ]
