# Generated by Django 5.2.5 on 2025-10-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role_alter_user_is_active'),
    ]

    operations = [
    ]
