# Generated by Django 5.2.6 on 2025-10-06 05:51

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251002_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(default=datetime.datetime.now, editable=False)),
                ('update_at', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('authors', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
                ('is_public', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('add_by', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
