# Generated by Django 5.2.5 on 2025-10-08 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alt_title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('language', models.DateField(default='cor')),
                ('total_chapter', models.BigIntegerField(default=0)),
                ('webtoon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webtoon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
