# Generated by Django 5.2.5 on 2025-10-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='language',
            field=models.CharField(default='cor', max_length=12),
        ),
        migrations.AlterField(
            model_name='release',
            name='total_chapter',
            field=models.IntegerField(default=0),
        ),
    ]
