# Generated by Django 5.2.5 on 2025-10-10 12:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_release_language_alter_release_total_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter_read', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('reading_status', models.CharField(choices=[('finish', 'Finish'), ('reading', 'Reading'), ('to read', 'To read')])),
                ('release_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.release')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
