# Generated by Django 5.2.5 on 2025-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='genres',
            field=models.ManyToManyField(related_name='webtoon', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='status',
            field=models.CharField(choices=[('finish', 'Finish'), ('in progress', 'In progress'), ('pause', 'Pause')], max_length=32),
        ),
    ]
