# Generated by Django 5.2.5 on 2025-10-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_webtoon_genres_alter_webtoon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='webtoon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release', to='api.webtoon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userrelease',
            name='release_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelease', to='api.release', unique=True),
        ),
        migrations.AlterField(
            model_name='userrelease',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userrelease',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelease', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='status',
            field=models.CharField(choices=[('finish', 'Finish'), ('in progress', 'In progress'), ('pause', 'Pause'), ('cancel', 'Cancel')], max_length=32),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
