# Generated by Django 5.2.5 on 2025-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_genre_update_at_alter_release_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelease',
            name='personal_total_chapter',
            field=models.IntegerField(default=0),
        ),
    ]
