# Generated by Django 5.2.5 on 2025-10-29 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userrelease_personal_total_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelease',
            name='release_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrelease', to='api.release'),
        ),
    ]
