# Generated by Django 5.2.18 on 2026-10-07 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userrelease_release_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='add_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_webtoons', to=settings.AUTH_USER_MODEL),
        ),
    ]
