# Generated by Django 5.2.18 on 2026-10-07 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_release_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='add_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='waiting_review',
            field=models.BooleanField(default=False),
        ),
    ]
