# Generated by Django 5.2.18 on 2026-10-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_release_submissions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrelease',
            constraint=models.UniqueConstraint(fields=('user_id', 'release_id'), name='unique_userrelease_per_user'),
        ),
    ]
