# Generated by Django 5.2.18 on 2026-10-08 16:43

from django.db import migrations, models
from django.db.models import Avg


def compute_ratings(apps, schema_editor):
    """Replace the hand written ratings by the average of the readers (same rule as api/ratings.py)."""
    Webtoon = apps.get_model("api", "Webtoon")
    UserRelease = apps.get_model("api", "UserRelease")
    for webtoon in Webtoon.objects.all():
        per_user = (
            UserRelease.objects.filter(release_id__webtoon_id=webtoon.pk, rating__gt=0)
            .values("user_id")
            .annotate(user_rating=Avg("rating"))
        )
        ratings = [row["user_rating"] for row in per_user]
        webtoon.rating = round(sum(ratings) / len(ratings), 2) if ratings else 0.0
        webtoon.rating_count = len(ratings)
        webtoon.save(update_fields=["rating", "rating_count"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_value_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(compute_ratings, migrations.RunPython.noop),
    ]
