# Generated by Django 5.2.18 on 2026-10-08 16:53

import api.models.user_release
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_webtoon_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelease',
            name='rating',
            field=models.FloatField(default=0.0, validators=[api.models.user_release.validate_user_rating]),
        ),
    ]
