# Generated by Django 5.2.18 on 2026-10-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_rating_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
