# Generated by Django 5.2.18 on 2026-10-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_webtoon_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='anilist_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='mangaupdates_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
